### ISSUE TITLE
Design: Structured Knockout Scheduler

### ISSUE THREAD

**Issue by PeterJCLaw** [PeterJCLaw/srcomp#49]
Currently there are two knockout schedulers. These work in quite different ways, though happily the internal interface is now fairly well defined. We know that the automatic scheduler is basically fine for simple cases, however we have enjoyed the flexibility of the static scheduler for exploring alternatives. The static scheduler however has some significant weaknesses compared to the rest of the system, most notably that it completely ignores match periods and delays, making it laborious to work with.

I'm proposing therefore to introduce a _structured_ scheduler which will work much more like the league matches, while still allowing for some of the knockout-specific functionality we want.

Features:
- input is rounds of matches specified in terms of their conceptual teams (i.e: seed or by reference to a prior match)
- rounds are optionally named (#48)
- matches are optionally named
- gaps between rounds can be specified, with some mechanism for absorbing delays in these gaps
- timings are automatically determined from the knockouts period's timing, delays automatically apply
- static corner allocation (i.e: exactly as league & static scheduler matches currently work)

Unknowns:
- how to specify gaps between rounds, how to work out which gaps can flex to absorb delays (and how to specify that)
- at what level to specify the arena to use; do we want to allow multi-arena usage? (I think we probably do, and probably want this at the match level as that's most flexible)

Rough example schema:
```
# knockouts.yaml
rounds:  # maps round number to round info
  0:
    display_name: Foo   # type: NotRequired[str]
    matches:  # maps local match number to match info
      0:
        display_name: Foo   # type: NotRequired[str]
        teams:  # type: list[TeamReference]
          - {seed: 0}
          - {round: 0, match: 0, position: 0}
```

Currently I'm torn between using the more verbose spelling here of the team references and the forms used in the static scheduler.

Related links:
- https://github.com/srobo/sr2025-comp/pull/16
- https://github.com/PeterJCLaw/srcomp/issues/48
- https://github.com/PeterJCLaw/srcomp/issues/8
- https://studentrobotics.slack.com/archives/C3190DWP3/p1743810047628639

**Comment by PeterJCLaw** [comment]
@prophile @samjmartin04 would be great to get your thoughts on this at some point.

**Comment by PeterJCLaw** [comment]
Aaand I've just realised that the structure I outlined above doesn't account for multi-arena setups.

**Comment by PeterJCLaw** [comment]
Here's what a config accounting for arenas might look like:
```yaml
# knockouts.yaml
structured_knockout:
  rounds:
    # round number
    0:
      display_name: Heats
      match_slots:
        # match number within the round
        0:
          A:
            display_name: Qualifier 1
            teams:
            - seed: 3
            - seed: 5
            - seed: 8
            - seed: 10
          B:
            display_name: Qualifier 2
            teams:
            - seed: 4
            - seed: 6
            - seed: 7
            - seed: 9
    1:
      match_slots:
        0:
          A:
            teams:
            # Reference a seeded team directly. Seeds are 1-indexed.
            - seed: 2
            # Reference the outcome from a previous knockout match. Positions are 0-indexed.
            - {round: 0, slot: 0, arena: A, position: 0}
            - {round: 0, slot: 0, arena: A, position: 2}
            - {round: 0, slot: 1, arena: A, position: 1}
        1:
          A:
            teams:
            - seed: 1
            - {round: 0, slot: 0, arena: A, position: 1}
            - {round: 0, slot: 1, arena: A, position: 0}
            - {round: 0, slot: 1, arena: A, position: 2}
    2:
      display_name: Finals
      match_slots:
        0:
          A:
            teams:
            - {round: 1, slot: 0, arena: A, position: 0}
            - {round: 1, slot: 0, arena: A, position: 1}
            - {round: 1, slot: 1, arena: A, position: 0}
            - {round: 1, slot: 1, arena: A, position: 1}
```
